"""VecNormalize 통계를 코드에 굽기 위한 상수 블록 생성기.

공식 채점기(evaluate.py)는 `PPO.load(zip)`만 하고 VecNormalize pkl을 읽지 않는다.
따라서 관측 정규화를 환경 쪽(custom_observation)에서 직접 수행해야 하며,
그 통계를 custom_walker2d.py 안에 상수로 심는다.

사용:
  python bake_norm.py --pkl checkpoints/bump_challenge_v9_8bumps_final/walker_model_vecnormalize_2600000_steps.pkl
출력된 블록을 custom_walker2d.py의 OBS_NORM_MEAN / OBS_NORM_VAR 자리에 붙여넣는다.
"""
import argparse
import pickle

import numpy as np


def fmt(name, arr):
    body = ",\n    ".join(", ".join(f"{float(v):.6f}" for v in arr[i:i + 5])
                          for i in range(0, len(arr), 5))
    return f"{name} = np.array([\n    {body}\n])"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pkl", required=True)
    args = p.parse_args()

    with open(args.pkl, "rb") as f:
        vn = pickle.load(f)
    mean = np.asarray(vn.obs_rms.mean, dtype=np.float64)
    var = np.asarray(vn.obs_rms.var, dtype=np.float64)
    print(f"# generated by bake_norm.py from {args.pkl}")
    print(f"# obs dim = {len(mean)}, clip_obs = {vn.clip_obs}, epsilon = {vn.epsilon}")
    print(fmt("OBS_NORM_MEAN", np.round(mean, 6)))
    print(fmt("OBS_NORM_VAR", np.round(var, 6)))


if __name__ == "__main__":
    main()
